name: Build App
on:
  push:
    branches:
      - main
    paths:
      - app/**
      - .github/workflows/build-docker-app.yml
  workflow_dispatch:

concurrency:
  group: "website-deploy"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: monsieurlazar/provocari-digitale
          DIR: app
        run: |
          sudo docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          sudo docker build --pull --cache-from $IMAGE_NAME \
            --tag $IMAGE_NAME:$GITHUB_SHA \
            --tag $IMAGE_NAME:latest \
            . -f ./$DIR/Dockerfile
          sudo docker push $IMAGE_NAME:$GITHUB_SHA
          sudo docker push $IMAGE_NAME:latest
      - name: Update Docker Container
        if: success()
        env:
          CONTAINER_NAME: provocari-digitale
          IMAGE_NAME: monsieurlazar/provocari-digitale
          TRAEFIK_ROUTER_NAME: provocari-digitale
          DOMAIN: ctf.bylazar.com
          PORT: 80
        run: |
          sudo docker stop $CONTAINER_NAME || true
          sudo docker rm --force $CONTAINER_NAME || true
          sudo docker rmi $IMAGE_NAME || true
          sudo docker run --detach --restart always --network lazar-network \
            --label traefik.enable=true \
            --label traefik.http.routers.$TRAEFIK_ROUTER_NAME.entrypoints=http,https \
            --label traefik.http.routers.$TRAEFIK_ROUTER_NAME.rule=Host\(\`$DOMAIN\`\) \
            --label traefik.http.routers.$TRAEFIK_ROUTER_NAME.tls=true \
            --label traefik.http.routers.$TRAEFIK_ROUTER_NAME.tls.certresolver=cloudflare \
            --label traefik.http.services.$TRAEFIK_ROUTER_NAME.loadbalancer.server.port=$PORT \
            --name $CONTAINER_NAME $IMAGE_NAME:latest
